services:
  grafana:
    user: root
    container_name: 'grafana-business-text-panel'
    image: grafana/${GRAFANA_IMAGE:-grafana-enterprise}:${GRAFANA_VERSION:-latest}
    ports:
      - 3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/marcusolsson-dynamictext-panel
      - ../provisioning:/etc/grafana/provisioning
    environment:
      NODE_ENV: development
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ENABLED: ${ANONYMOUS_AUTH_ENABLED:-true}
      GF_AUTH_BASIC_ENABLED: "false"
      GF_DEFAULT_APP_MODE: development
      GF_LOG_FILTERS: plugin.marcusolsson-dynamictext-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: marcusolsson-dynamictext-panel
      GF_INSTALL_PLUGINS: marcusolsson-static-datasource,volkovlabs-rss-datasource,yesoreyeram-infinity-datasource
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

